### PR TITLE
mpnowacki's key

### PR DESCRIPTION
**Pull request by mpnowacki-reef**

### CODE REVIEW

**Review by mlech-reef — APPROVED** [review]

**Comment by agoncharov-reef** [comment]
BTW is it okay to spoil emails like that?

**Comment by mpnowacki-reef** [comment]
@agoncharov-reef what do you mean?

**Comment by agoncharov-reef** [comment]
Paradise for spammers, all emails as plain text

Screenshot_2021-03-12_14-05-47

**Comment by ppolewicz** [comment]
@mpnowacki-reef please also update `index.md`

@agoncharov-reef you are correct, we'll fix it in a separate PR

**Comment by mpnowacki-reef** [comment]
@ppolewicz How should we deal with name ambiguity? Should I rename `Michal` in `index.md` to `Michal Ż` or `Odd Michal` ?

**Comment by ppolewicz** [comment]
@mpnowacki-reef `Michal Z` and `Michal N`, please

**Review by ppolewicz — APPROVED** [review]

**Pull request merged**
